#!/usr/bin/env python3

import sys
import os

from find_duplicate_files_in_folder import generate_match_dict


if __name__ == '__main__':

    path = bytes(sys.argv[1], 'UTF8')
    path = os.path.realpath(path)

    match_dict = generate_match_dict(path)

    for key in match_dict.keys():
        print('\n'+key+":")
        files = match_dict[key]
        print("files:", files)

        file_to_keep = min(files, key=len)
        print("file_to_keep:", file_to_keep)

        files.remove(file_to_keep)
        print("rm:", files)
        for file in files:
#           print("about to rm", file)
            os.remove(file)
