#!/usr/bin/env python3

import glob
import sys
import os
import pickle
import hashlib

import sqlite3
#conn = sqlite3.connect('/home/user/cfg/_myapps/fsindex/all_paths_from_pickle_try2_blobs.db')
#conn = sqlite3.connect('/home/user/cfg/_myapps/fsindex/_good/fsindex.sha1.db')
conn = sqlite3.connect('/home/user/.fsindex/_good/fsindex.sha1.db')

c = conn.cursor()

#c.execute('''CREATE TABLE path_db (id TEXT, full_path BLOB, file_name BLOB, st_mode INT, st_ino INT, st_dev INT, st_nlink INT, st_uid INT, st_gid INT, st_size INT, st_atime REAL, st_mtime REAL, st_ctime REAL)''')
#c.execute("PRAGMA synchronous = OFF")

file = bytes(sys.argv[1], 'UTF8')
#file = os.path.realpath(file)
#filename = file.split(b'/')[-1]
#filestat = os.stat(file)

print("searching for:", file, "...")

#print(filestat)

#answer = c.execute('''SELECT full_path, file_name, st_size FROM path_db WHERE file_name=?''', (b"explore3d.m.txt",))
answer = c.execute('''SELECT full_path, file_name, st_size FROM path_db WHERE file_name LIKE ?''', (b'%'+file+b'%',))

#print(answer.fetchone())


for result in answer.fetchall():
    print(result)
    continue
    os._exit(1)

