#!/usr/bin/env python3

import sys
import os

from .dbconnection import c

#import sqlite3
#conn = sqlite3.connect('/home/user/.fsindex/_good/fsindex.sha1.db')
#c = conn.cursor()

file = bytes(sys.argv[1], 'UTF8')

query = '''SELECT * FROM path_db WHERE file_name=?'''
answer = c.execute(query, (file,))

for result in answer.fetchall():
	print(result)

